### ISSUE TITLE
Clarify how to add API credentials

### ISSUE THREAD

**Issue by alex-steinberg** [ChrisBooth360/nest-trello-app#2]
Getting the API key etc isn't straightforward. This [link](https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/#managing-your-api-key) is where I started. Perhaps the readme could do with some more steps?

**Comment by ChrisBooth360** [comment]
It is a confusing process with Trello - it took me a while to figure it out, so I definitely can add the steps to the readme. Or would it be better to provide the API key and token that I was using when I was building the application? I know that those should be secret, that's why I didn't include them.
